# version: "3.9"
services:
  mariadb:
    image: mariadb:11.3
    container_name: mariadb
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      retries: 5
      start_period: 10s
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ischeroth_infos
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  backend:
      build:
        context: ./spring-backend
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        mariadb:
          condition: service_healthy
      env_file:
        - .env
      environment:
        SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE}
        SPRING_DATASOURCE_USERNAME: ${DATABASE_USER}
        SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
        SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ${DIALECT}

  # dev setup
  frontend:
    build:
      context: ./vue-frontend
      dockerfile: Dockerfile.dev
      # dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./vue-frontend:/app:delegated      # mount your code
      - /app/node_modules                  # keep container deps from being shadowed
    environment:
      - CHOKIDAR_USEPOLLING=true           # needed on some hosts/VMs
    command: npm run dev -- --host 0.0.0.0 # make Vite reachable from outside


volumes:
  db_data: