-- Create attributes table
CREATE TABLE IF NOT EXISTS attributes (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  short_name VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  value INTEGER NOT NULL, 
  increased BOOLEAN NOT NULL
);

-- Create skills table
CREATE TABLE IF NOT EXISTS skills (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  value INTEGER NOT NULL, 
  increased BOOLEAN NOT NULL,
  skill_group VARCHAR(255) NOT NULL,
  divisor INTEGER NOT NULL, 
  attributes VARCHAR(255) NOT NULL
);

-- Create name table
CREATE TABLE IF NOT EXISTS names (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  name_group VARCHAR(255) NOT NULL,
  gender VARCHAR(255) NOT NULL, 
  meaning VARCHAR(255) NOT NULL
);

-- Set attributes
INSERT INTO attributes (short_name, name, value, increased) VALUES
('Mu', 'Mut', 12, 0),
('Au', 'Aufmerksamkeit', 12, 0),
('Ve', 'Verstand', 12, 0),
('Ch', 'Charisma', 12, 0),
('Fi', 'Fingerfertigkeit', 12, 0),
('Ge', 'Gewandheit', 12, 0),
('St', 'Stärke', 12, 0),
('Ko', 'Konstitution', 12, 0);

-- Set skills
INSERT INTO skills (name, value, increased, skill_group, divisor, attributes) VALUES
('Robustheit', 12, 0, 'Grundwert', 3, 'St,Ko,Ko'),
('Bewegung', 7, 0, 'Grundwert', 5, 'Au,Ge,Ge'),
('Mumm', 7, 0, 'Grundwert', 5, 'Mu,Mu,Ve'),
('Reflexe', 12, 0, 'Grundwert', 3, 'Au,Ve,Ge'),
('Sprachbegabung', 12, 0, 'Grundwert', 3, 'Au,Ve,Ch'),
('Dolch & Fechtwaffen', 12, 0, 'Kampf', 2, 'Mu,Fi,Ge'),
('Hieb- & Kettenwaffen', 12, 0, 'Kampf', 2, 'Mu,St,Ko'),
('Raufen & Ringen', 12, 0, 'Kampf', 2, 'Mu,Ge,St'),
('Säbel & Schwerter', 12, 0, 'Kampf', 2, 'Mu,Ge,St'),
('Speere & Stäbe', 12, 0, 'Kampf', 2, 'Mu,Fi,St'),
('Schilde', 12, 0, 'Kampf', 2, 'Au,St,Ko'),
('Armbrust', 12, 0, 'Kampf', 2, 'Au,Fi,St'),
('Bogen', 12, 0, 'Kampf', 2, 'Au,Ge,St'),
('Feuerrohre', 12, 0, 'Kampf', 2, 'Au,Ve,Fi'),
('Wurf & Schleuderwaffen', 12, 0, 'Kampf', 2, 'Au,Fi,Ge'),
('Akrobatik', 12, 0, 'Körper', 3, 'Mu,Ge,St'),
('Athletik', 12, 0, 'Körper', 3, 'Ge,St,Ko'),
('Diebeskunst', 12, 0, 'Körper', 3, 'Au,Ve,Fi'),
('Heimlichkeit', 12, 0, 'Körper', 3, 'Mu,Au,Ge'),
('Horchen', 12, 0, 'Körper', 3, 'Au,Ve,Ko'),
('Klettern', 12, 0, 'Körper', 3, 'Mu,Ge,St'),
('Reiten', 12, 0, 'Körper', 3, 'Ch,Ge,St'),
('Schwimmen', 12, 0, 'Körper', 3, 'Ge,St,Ko'),
('Verborgenes Erkennen', 12, 0, 'Körper', 3, 'Mu,Au,Ve'),
('Zechen', 12, 0, 'Körper', 3, 'Mu,St,Ko'),
('Fährtensuche', 12, 0, 'Natur', 3, 'Au,Ve,Ko'),
('Fischen & Angeln', 12, 0, 'Natur', 3, 'Au,Fi,St'),
('Himmelskunde', 12, 0, 'Natur', 3, 'Au,Au,Ve'),
('Lager & Rasten', 12, 0, 'Natur', 3, 'Au,Ge,Ko'),
('Orientierung', 12, 0, 'Natur', 3, 'Au,Au,Ve'),
('Pflanzenkunde', 12, 0, 'Natur', 3, 'Au,Ve,Fi'),
('Tierkunde', 12, 0, 'Natur', 3, 'Mu,Ve,Ch'),
('Alchemie', 12, 0, 'Handwerk', 3, 'Mu,Ve,Fi'),
('Boot- & Seefahrt', 12, 0, 'Handwerk', 3, 'Au,Ge,Ko'),
('Fahrzeug lenken', 12, 0, 'Handwerk', 3, 'Au,Ch,Fi'),
('Holzbearbeitung', 12, 0, 'Handwerk', 3, 'Ve,Fi,St'),
('Kochen & Brauen', 12, 0, 'Handwerk', 3, 'Ve,Fi,Fi'),
('Lehm- & Steinbearbeitung', 12, 0, 'Handwerk', 3, 'Ve,Fi,Fi'),
('Malen & Zeichnen', 12, 0, 'Handwerk', 3, 'Au,Fi,Fi'),
('Singen & Musizieren', 12, 0, 'Handwerk', 3, 'Au,Ch,Fi'),
('Schmiedekunst', 12, 0, 'Handwerk', 3, 'Fi,St,Ko'),
('Schneider- & Lederarbeiten', 12, 0, 'Handwerk', 3, 'Ve,Fi,Ko'),
('Einschüchtern', 12, 0, 'Gesellschaft', 3, 'Mu,Ch,St'),
('Handel', 12, 0, 'Gesellschaft', 3, 'Au,Ve,Ch'),
('Schauspielerei', 12, 0, 'Gesellschaft', 3, 'Mu,Ve,Ch'),
('Standeswissen', 12, 0, 'Gesellschaft', 3, 'Au,Ve,Ch'),
('Tanzen', 12, 0, 'Gesellschaft', 3, 'Ch,Ge,Ge'),
('Überreden', 12, 0, 'Gesellschaft', 3, 'Mu,Au,Ch'),
('Überzeugen', 12, 0, 'Gesellschaft', 3, 'Au,Ve,Ch'),
('Architekt', 12, 0, 'Wissen', 3, 'Ve,Ve,Fi'),
('Geschichtswissen', 12, 0, 'Wissen', 3, 'Au,Ve,Ve'),
('Götter & Kulte', 12, 0, 'Wissen', 3, 'Ve,Ve,Ch'),
('(Heil-)Kunde des Geistes', 12, 0, 'Wissen', 3, 'Ve,Ve,Ch'),
('(Heil-)Kunde des Körpers', 12, 0, 'Wissen', 3, 'Ve,Ve,Fi'),
('Kriegskunst', 12, 0, 'Wissen', 3, 'Mu,Ve,Ch'),
('Magiekunde', 12, 0, 'Wissen', 3, 'Au,Ve,Ve'),
('Rechnen & Physik', 12, 0, 'Wissen', 3, 'Ve,Ve,Fi'),
('Rechts- & Staatskunst', 12, 0, 'Wissen', 3, 'Ve,Ve,Ch');

INSERT INTO names (name, name_group, gender, meaning) VALUES
('Alrik', 'human', 'male', ''),
('Alrika', 'human', 'female', ''),
('Damila', 'human', 'female', ''),
('Grukk', 'dwarf', 'neutral', ''),
('Toval', 'dwarf', 'neutral', ''),
('Krinn', 'dwarf', 'neutral', ''),
('Skarn', 'dwarf', 'neutral', ''),
('Brath', 'dwarf', 'neutral', ''),
('Vorn', 'dwarf', 'neutral', ''),
('Dregga', 'dwarf', 'neutral', ''),
('Orvak', 'dwarf', 'neutral', ''),
('Frikka', 'dwarf', 'female', ''),
('Thilda', 'dwarf', 'female', ''),
('Bruni', 'dwarf', 'female', ''),
('Orla', 'dwarf', 'female', ''),
('Skada', 'dwarf', 'female', ''),
('Gudrin', 'dwarf', 'female', ''),
('Trisla', 'dwarf', 'female', ''),
('Velka', 'dwarf', 'female', ''),
('Kormi', 'dwarf', 'female', ''),
('Dagna', 'dwarf', 'female', ''),
('Brynja', 'dwarf', 'female', ''),
('Frola', 'dwarf', 'female', ''),
('Grida', 'dwarf', 'female', ''),
('Harkja', 'dwarf', 'female', ''),
('Svinna', 'dwarf', 'female', ''),
('Torka', 'dwarf', 'female', ''),
('Varka', 'dwarf', 'female', ''),
('Frundra', 'dwarf', 'female', ''),
('Blikka', 'dwarf', 'female', ''),
('Malvi', 'dwarf', 'female', ''),
('Gríma', 'dwarf', 'female', ''),
('Frida', 'dwarf', 'female', ''),
('Dís', 'dwarf', 'female', ''),
('Nori', 'dwarf', 'female', ''),
('Farin', 'dwarf', 'female', ''),
('Korrin', 'dwarf', 'male', ''),
('Thrak', 'dwarf', 'male', ''),
('Beldur', 'dwarf', 'male', ''),
('Dromak', 'dwarf', 'male', ''),
('Frorin', 'dwarf', 'male', ''),
('Gundrik', 'dwarf', 'male', ''),
('Thavur', 'dwarf', 'male', ''),
('Brokk', 'dwarf', 'male', ''),
('Maldin', 'dwarf', 'male', ''),
('Skorik', 'dwarf', 'male', ''),
('Orvik', 'dwarf', 'male', ''),
('Gralin', 'dwarf', 'male', ''),
('Trundar', 'dwarf', 'male', ''),
('Falkrim', 'dwarf', 'male', ''),
('Dravok', 'dwarf', 'male', ''),
('Borik', 'dwarf', 'male', ''),
('Krandar', 'dwarf', 'male', ''),
('Vuldin', 'dwarf', 'male', ''),
('Thrumm', 'dwarf', 'male', ''),
('Ragnik', 'dwarf', 'male', ''),
('Durin', 'dwarf', 'male', ''),
('Thrain', 'dwarf', 'male', ''),
('Orin', 'dwarf', 'male', ''),
('Balin', 'dwarf', 'male', ''),
('Fundin', 'dwarf', 'male', ''),
('Aevir', 'elf', 'neutral', ''),
('Delynth', 'elf', 'neutral', ''),
('Sylareth', 'elf', 'neutral', ''),
('Orthwen', 'elf', 'neutral', ''),
('Calisra', 'elf', 'neutral', ''),
('Thyrin', 'elf', 'neutral', ''),
('Elarin', 'elf', 'neutral', ''),
('Vanyth', 'elf', 'neutral', ''),
('Cyrithiel', 'elf', 'neutral', ''),
('Talyon', 'elf', 'neutral', ''),
('Mirwyn', 'elf', 'neutral', ''),
('Arlyth', 'elf', 'neutral', ''),
('Fenrisel', 'elf', 'neutral', ''),
('Lioraeth', 'elf', 'neutral', ''),
('Selivrae', 'elf', 'neutral', ''),
('Othryn', 'elf', 'neutral', ''),
('Feylan', 'elf', 'neutral', ''),
('Yllarith', 'elf', 'neutral', ''),
('Larethiel', 'elf', 'neutral', ''),
('Phylaris', 'elf', 'neutral', ''),
('Nymrae', 'elf', 'neutral', ''),
('Lyrielle', 'elf', 'female', ''),
('Thalindra', 'elf', 'female', ''),
('Emythrae', 'elf', 'female', ''),
('Serelith', 'elf', 'female', ''),
('Vaenira', 'elf', 'female', ''),
('Althwyn', 'elf', 'female', ''),
('Elenara', 'elf', 'female', ''),
('Myrineth', 'elf', 'female', ''),
('Caelwyn', 'elf', 'female', ''),
('Aelthir', 'elf', 'male', ''),
('Vaelorin', 'elf', 'male', ''),
('Thandrel', 'elf', 'male', ''),
('Eryndor', 'elf', 'male', ''),
('Calveth', 'elf', 'male', ''),
('Sylorin', 'elf', 'male', ''),
('Faelrun', 'elf', 'male', ''),
('Orvenis', 'elf', 'male', ''),
('Draylin', 'elf', 'male', ''),
('Bryndor', 'elf', 'male', ''),
('Tanuen', 'felida', 'neutral', ''),
('Bhairita', 'felida', 'neutral', ''),
('Devium', 'felida', 'neutral', ''),
('Masha', 'felida', 'neutral', ''),
('Victlakun', 'felida', 'neutral', ''),
('Octorix', 'felida', 'neutral', ''),
('Rajelun', 'felida', 'neutral', ''),
('Flavanis', 'felida', 'neutral', ''),
('Cornlaksha', 'felida', 'neutral', ''),
('Domun', 'felida', 'neutral', ''),
("Aure'enis", 'felida', 'neutral', ''),
('Nilora', 'felida', 'female', ''),
('Jayamala', 'felida', 'female', ''),
("Mala(')issa", 'felida', 'female', ''),
('Aniktara', 'felida', 'female', ''),
('Lucshree', 'felida', 'female', ''),
('Venshira', 'felida', 'female', ''),
('Octamanora', 'felida', 'female', ''),
('Claudinita', 'felida', 'female', ''),
('Survaljaya', 'felida', 'female', ''),
('Aurellata', 'felida', 'female', ''),
("Shi'ina", 'felida', 'female', ''),
('Rajanus', 'felida', 'male', ''),
('Devellus', 'felida', 'male', ''),
('Surindrajit', 'felida', 'male', ''),
('Domelraj', 'felida', 'male', ''),
('Victovirraj', 'felida', 'male', ''),
('Kumorix', 'felida', 'male', ''),
('Marvaldus', 'felida', 'male', ''),
('Aurelmirban', 'felida', 'male', ''),
('Lucindra', 'felida', 'male', ''),
('Corneliusban', 'felida', 'male', ''),
('Nila’actus', 'felida', 'male', ''),
('Qullayk', 'charaki', 'neutral', 'Speerschwanz'),
('Chaskir', 'charaki', 'neutral', 'Splitter des Sturms'),
('Khatruq', 'charaki', 'neutral', 'Schlag des Meeres'),
('Ruqay', 'charaki', 'neutral', 'der Zerreißende'),
('Shullkaq', 'charaki', 'neutral', 'der Gleiten-Schnelle'),
('Tayrak', 'charaki', 'neutral', 'Flosse, die schlägt'),
('Qishllu', 'charaki', 'neutral', 'der/die Schuppige'),
('Challwaq', 'charaki', 'neutral', 'die Jägerin der Fische'),
('Qhurmak', 'charaki', 'neutral', 'Kampfstrom'),
("T'unyash", 'charaki', 'neutral', 'die Zermalmende'),
('Kulltur', 'charaki', 'neutral', 'der Scharfzahn'),
('Qarpayk', 'charaki', 'neutral', 'Klaue des Wassers'),
('Saqrayuq', 'charaki', 'neutral', 'Besitzende des Dämons'),
('Yalltik', 'charaki', 'neutral', 'Splitterflosse'),
('Chuklik', 'charaki', 'neutral', 'die Zornige'),
('Pakayuq', 'charaki', 'neutral', 'die Verborgene'),
('Shirpayk', 'charaki', 'neutral', 'die Stachelige'),
("Q'illkayk", 'charaki', 'neutral', 'die Vernarbte'),
("T'ayquk", 'charaki', 'neutral', 'Wellenbrecher'),
('Ruptayuq', 'charaki', 'neutral', 'die Zerteilende'),
('Llaktik', 'charaki', 'neutral', 'die aus der Siedlung'),
("Q'umirquk", 'charaki', 'neutral', 'die Grünglänzende'),
('Chiriyak', 'charaki', 'neutral', 'die Kalte'),
('Shukkak', 'charaki', 'neutral', 'die mit einem Auge'),
('Kushrak', 'charaki', 'neutral', 'die Beißende'),
('Chuqllayk', 'charaki', 'neutral', 'die Schleimige'),
("T'arayuq", 'charaki', 'neutral', 'die mit der Harpune'),
('Murqayk', 'charaki', 'neutral', 'die mit dem Strudel'),
('Qiripayk', 'charaki', 'neutral', 'die Knochige'),
('Chaskiyuq', 'charaki', 'neutral', 'Besitzerin der Sterne'),
('Bal', 'goblin', 'neutral', ''),
('Rag', 'goblin', 'neutral', ''),
('Jub', 'goblin', 'neutral', ''),
('Zorg', 'goblin', 'neutral', ''),
('Gud', 'goblin', 'neutral', ''),
('Daz', 'goblin', 'neutral', ''),
('Vug', 'goblin', 'neutral', ''),
('Zug', 'goblin', 'neutral', ''),
('Gor', 'goblin', 'neutral', ''),
('Dub', 'goblin', 'neutral', ''),
('Baz', 'goblin', 'neutral', ''),
('Rud', 'goblin', 'neutral', ''),
('Gul', 'goblin', 'neutral', ''),
('Mog', 'goblin', 'neutral', ''),
('Feg', 'goblin', 'neutral', ''),
('Bog', 'goblin', 'neutral', ''),
('Dug', 'goblin', 'neutral', ''),
('Rag', 'goblin', 'neutral', ''),
('Sab', 'goblin', 'neutral', ''),
('Zin', 'goblin', 'neutral', ''),
('Zug’Ral', 'goblin', 'neutral', ''),
('Bal’Tor', 'goblin', 'neutral', ''),
('Rag’Bin', 'goblin', 'neutral', ''),
('Feg’Lum', 'goblin', 'neutral', ''),
('Vur’Lin', 'goblin', 'neutral', ''),
('Dug’Bar', 'goblin', 'neutral', ''),
('Mog’Nir', 'goblin', 'neutral', ''),
('Zin’Gol', 'goblin', 'neutral', ''),
('Dub’Tan', 'goblin', 'neutral', ''),
('Naz’Gi', 'goblin', 'neutral', ''),
('Gud’Mar', 'goblin', 'neutral', ''),
('Sab’Lon', 'goblin', 'neutral', ''),
('Gor’Vul', 'goblin', 'neutral', ''),
('Mog’Zin', 'goblin', 'neutral', ''),
('Gud’Fen', 'goblin', 'neutral', ''),
('Zin’Bor', 'goblin', 'neutral', ''),
('Zul’Bag', 'goblin', 'neutral', ''),
('Sira', 'goblin', 'female', ''),
('Vaga', 'goblin', 'female', ''),
('Zuba', 'goblin', 'female', ''),
('Dura', 'goblin', 'female', ''),
('Rida', 'goblin', 'female', ''),
('Gula', 'goblin', 'female', ''),
('Faza', 'goblin', 'female', ''),
('Bega', 'goblin', 'female', ''),
('Luba', 'goblin', 'female', ''),
('Suda', 'goblin', 'female', ''),
('Moga', 'goblin', 'female', ''),
('Naga', 'goblin', 'female', ''),
('Jina', 'goblin', 'female', ''),
('Daga', 'goblin', 'female', ''),
('Bira', 'goblin', 'female', ''),
('Tula', 'goblin', 'female', ''),
('Zina', 'goblin', 'female', ''),
('Paga', 'goblin', 'female', ''),
('Raga', 'goblin', 'female', ''),
('Gida', 'goblin', 'female', ''),
('Sira’Baz', 'goblin', 'female', ''),
('Vaga’Lin', 'goblin', 'female', ''),
('Zuba’Ren', 'goblin', 'female', ''),
('Dura’Fen', 'goblin', 'female', ''),
('Rida’Gol', 'goblin', 'female', ''),
('Gula’Sin', 'goblin', 'female', ''),
('Faza’Lor', 'goblin', 'female', ''),
('Bega’Min', 'goblin', 'female', ''),
('Luba’Tal', 'goblin', 'female', ''),
('Suda’Var', 'goblin', 'female', ''),
('Moga’Dil', 'goblin', 'female', ''),
('Naga’Bil', 'goblin', 'female', ''),
('Jina’Roz', 'goblin', 'female', ''),
('Daga’Mel', 'goblin', 'female', ''),
('Bira’Pon', 'goblin', 'female', ''),
('Tula’Gim', 'goblin', 'female', ''),
('Zina’Bor', 'goblin', 'female', ''),
('Paga’Nel', 'goblin', 'female', ''),
('Raga’Zum', 'goblin', 'female', ''),
('Gida’Fal', 'goblin', 'female', ''),
('Jub’Nag', 'goblin', 'male', ''),
('Pag’Dor', 'goblin', 'male', ''),
('Gor’Dim', 'goblin', 'male', ''),
('Bag’Zor', 'goblin', 'male', ''),
('Ul’Sag', 'goblin', 'male', ''),
('Sab’Rig', 'goblin', 'male', ''),
('Rag’Mol', 'goblin', 'male', ''),
('Nab’Tur', 'goblin', 'male', ''),
('Bog’Lar', 'goblin', 'male', ''),
('Naz’Gil', 'goblin', 'male', ''),
('Rib’Gul', 'goblin', 'male', ''),
('Feg’Dur', 'goblin', 'male', ''),
('Lug’Ban', 'goblin', 'male', ''),
('Dur’Fal', 'goblin', 'male', ''),
('Buz’Ram', 'goblin', 'male', ''),
('Harti', 'harakhaya', 'neutral', ''),
('Si(h)ba', 'harakhaya', 'neutral', ''),
('Bira', 'harakhaya', 'neutral', ''),
('Ma(h)ba', 'harakhaya', 'neutral', ''),
('Bash', 'harakhaya', 'neutral', ''),
('Hihisa', 'harakhaya', 'neutral', ''),
('Risara', 'harakhaya', 'neutral', ''),
('Hamina', 'harakhaya', 'neutral', ''),
('Higari', 'harakhaya', 'neutral', ''),
('Parapi', 'harakhaya', 'neutral', ''),
('Gihali', 'harakhaya', 'neutral', ''),
('Hihisa', 'harakhaya', 'neutral', ''),
('Kihaba', 'harakhaya', 'neutral', ''),
('Tahika', 'harakhaya', 'neutral', ''),
('Hebija', 'harakhaya', 'neutral', ''),
('Hartiru(h)na', 'harakhaya', 'neutral', ''),
('Risirohi', 'harakhaya', 'neutral', ''),
('Ramikuji', 'harakhaya', 'neutral', ''),
('Letosima', 'harakhaya', 'neutral', ''),
('Kiarsiko', 'harakhaya', 'neutral', ''),
('Giniaxki', 'harakhaya', 'neutral', ''),
('Hohimihar', 'harakhaya', 'neutral', ''),
('Rebapima', 'harakhaya', 'neutral', ''),
('Kikirara', 'harakhaya', 'neutral', ''),
('Ma’axaxhi', 'harakhaya', 'neutral', ''),
('Harti', 'harakhaya', 'neutral', ''),
('Corneliusban', 'charaki', 'neutral', '');

